# Deliberate faults for tools/mutate.py: (name, exact snippet in the contract, replacement).
# Each must be caught by at least one test.
MUTATIONS = [
    ("BLOCKS_OTHERS never reaches the FRONT lane",
     "            if self.front_open.get(wkey, \"\") == \"\":\n                lane = LANE_FRONT",
     "            if self.front_open.get(wkey, \"\") == \"\":\n                lane = LANE_BACK"),
    ("SELF_ONLY also goes to the FRONT lane",
     "        if outcome == BLOCKS_OTHERS:\n            if self.front_open",
     "        if outcome == BLOCKS_OTHERS or outcome == SELF_ONLY:\n            if self.front_open"),
    ("no per-wallet front slot (every BLOCKS_OTHERS goes FRONT)",
     "            if self.front_open.get(wkey, \"\") == \"\":", "            if True:"),
    ("front slot not recorded when a FRONT ticket is filed",
     "            self.front_open[wkey] = tid\n", ""),
    ("note front_lane_taken not set",
     "                note = NOTE_FRONT_TAKEN", "                note = \"\""),
    ("lane overwrites the outcome",
     "            outcome=outcome,", "            outcome=BLOCKS_OTHERS if lane == LANE_FRONT else SELF_ONLY,"),
    ("take_next serves BACK before FRONT",
     "        if front_head < int(desk.front_len):", "        if front_head < int(desk.front_len) and back_head >= int(desk.back_len):"),
    ("BACK lane served last-in first-out",
     "            tid = self.lane_slots[self._slot_key(did, LANE_BACK, back_head)]",
     "            tid = self.lane_slots[self._slot_key(did, LANE_BACK, int(desk.back_len) - 1)]"),
    ("head pointer does not skip withdrawn tickets",
     "            if self.tickets[self.lane_slots[self._slot_key(did, lane, h)]].state == T_WAITING:",
     "            if self.tickets[self.lane_slots[self._slot_key(did, lane, h)]].state != \"\":"),
    ("front slot freed when the ticket is taken (IN_PROGRESS)",
     "        ticket.state = T_IN_PROGRESS\n",
     "        ticket.state = T_IN_PROGRESS\n        self.front_open[self._wallet_key(did, ticket.filer)] = \"\"\n"),
    ("front slot not freed on resolve",
     "            if self.front_open.get(wkey, \"\") == tid:\n                self.front_open[wkey] = \"\"",
     "            if self.front_open.get(wkey, \"\") == tid:\n                pass"),
    ("front slot not freed on withdraw",
     "        if ticket.lane == LANE_FRONT and self.front_open.get(wkey, \"\") == tid:\n            self.front_open[wkey] = \"\"",
     "        if ticket.lane == LANE_FRONT and self.front_open.get(wkey, \"\") == tid:\n            pass"),
    ("withdrawing a BACK ticket frees the front slot",
     "        if ticket.lane == LANE_FRONT and self.front_open.get(wkey, \"\") == tid:",
     "        if True:"),
    ("waiting cap off by one (4 waiting)",
     "        if int(self.waiting.get(wkey, u256(0))) >= MAX_WAITING_PER_WALLET:",
     "        if int(self.waiting.get(wkey, u256(0))) > MAX_WAITING_PER_WALLET:"),
    ("taking a ticket does not reduce the filer's waiting count",
     "        self._add_waiting(self._wallet_key(did, ticket.filer), -1)\n", ""),
    ("withdrawing does not reduce the waiting count",
     "        self._add_waiting(wkey, -1)\n", ""),
    ("desk cap off by one (201 tickets)",
     "        if int(desk.ticket_count) >= MAX_TICKETS_PER_DESK:", "        if int(desk.ticket_count) > MAX_TICKETS_PER_DESK:"),
    ("desk full checked before the waiting cap",
     "        if int(self.waiting.get(wkey, u256(0))) >= MAX_WAITING_PER_WALLET:\n            raise gl.vm.UserError(\"You already have three tickets waiting\")\n        if int(desk.ticket_count) >= MAX_TICKETS_PER_DESK:\n            raise gl.vm.UserError(\"This desk is full\")",
     "        if int(desk.ticket_count) >= MAX_TICKETS_PER_DESK:\n            raise gl.vm.UserError(\"This desk is full\")\n        if int(self.waiting.get(wkey, u256(0))) >= MAX_WAITING_PER_WALLET:\n            raise gl.vm.UserError(\"You already have three tickets waiting\")"),
    ("fail-safe flipped on unparseable output",
     "                    return {\"outcome\": SELF_ONLY}\n            if not isinstance(data, dict):",
     "                    return {\"outcome\": BLOCKS_OTHERS}\n            if not isinstance(data, dict):"),
    ("unknown label maps to BLOCKS_OTHERS",
     "            if outcome == BLOCKS_OTHERS:\n                return {\"outcome\": BLOCKS_OTHERS}\n            return {\"outcome\": SELF_ONLY}",
     "            if outcome == SELF_ONLY:\n                return {\"outcome\": SELF_ONLY}\n            return {\"outcome\": BLOCKS_OTHERS}"),
    ("validator accepts any valid label",
     "                return str(mine.get(\"outcome\", \"\")).strip().upper() == leader_outcome",
     "                return True"),
    ("anyone may take tickets",
     "        if caller != desk.owner:", "        if caller == \"\":"),
    ("anyone may resolve tickets",
     "        if caller != self.desks[ticket.desk_id].owner:", "        if caller == \"\":"),
    ("anyone may withdraw a ticket",
     "        if caller != ticket.filer:", "        if caller == \"\":"),
    ("an IN_PROGRESS ticket may be withdrawn",
     "        if ticket.state != T_WAITING:", "        if ticket.state == T_RESOLVED or ticket.state == T_WITHDRAWN:"),
    ("a WAITING ticket may be resolved",
     "        if ticket.state != T_IN_PROGRESS:", "        if ticket.state == T_RESOLVED:"),
    ("same request may be filed twice",
     "        if tid in self.tickets:", "        if tid in self.tickets and False:"),
    ("ticket id ignores whitespace normalization",
     "        tid = self._ticket_id(did, filer, self._normalize_text(clean))",
     "        tid = self._ticket_id(did, filer, clean)"),
    ("reserved token not checked on desk names",
     "            raise gl.vm.UserError(\"Desk name is too long\")\n        if self._contains_reserved_token(clean):",
     "            raise gl.vm.UserError(\"Desk name is too long\")\n        if False:"),
    ("request length cap off by one",
     "        if len(clean) > MAX_REQUEST_LENGTH:", "        if len(clean) >= MAX_REQUEST_LENGTH:"),
    ("fence strip: no gap and a single pass (cross-token rebuild survives)",
     "            cleaned = cleaned[:index] + \" \" + cleaned[index + len(token):]\n\n    def _fence_strip(self, value: str) -> str:\n        # Fixed point: repeat until nothing changes, so nested fragments\n        # such as \"<<TAG>TAG>\" cannot rebuild a marker after one pass.\n        cleaned = value\n        while True:\n            before = cleaned\n            for token in RESERVED_TOKENS:\n                cleaned = self._remove_token(cleaned, token)\n            if cleaned == before:\n                return \" \".join(cleaned.split())",
     "            cleaned = cleaned[:index] + cleaned[index + len(token):]\n\n    def _fence_strip(self, value: str) -> str:\n        cleaned = value\n        for token in RESERVED_TOKENS:\n            cleaned = self._remove_token(cleaned, token)\n        return \" \".join(cleaned.split())"),
    ("wallet leaks into the prompt",
     "        safe_request = self._fence_strip(request)",
     "        safe_request = self._fence_strip(request) + \" \" + str(gl.message.sender_address)"),
    ("lane state leaks into the prompt",
     "        outcome = self._judge(desk.name, clean)",
     "        outcome = self._judge(desk.name, clean + \" \" + (LANE_BACK if self.front_open.get(wkey, \"\") != \"\" else \"\"))"),
]
